version: '3'
services:
  web:
    build: .
    volumes: 
      - .:/opt/app
    ports: 
      - 3000:3000
    networks:
      - onboarding-rebase
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - onboarding-rebase
    volumes:
      - onboarding_data:/var/lib/postgresql/data
volumes:
  onboarding_data:
networks:
  onboarding-rebase:
    name: onboarding_rebase